import { GiftItem, UserProfile } from "./types";

export const initialUserProfile: UserProfile = {
  name: "Nguyễn Văn Vương",
  email: "vuongnv@viettelidc.com.vn",
  phone: "0965816033",
  mainBalance: 0,
  promoBalance: 33816210,
  points: 1000000,
};

export const sampleGifts: GiftItem[] = [
  // 1. Ăn uống
  {
    id: "niuben-so-diep",
    name: "Niuben Hotpot - E-Coupon ưu đãi tặng 1 phần chả sò điệp cho nhóm 02 khách",
    points: 1500,
    category: "Ăn uống",
    giftType: "Voucher ăn uống",
    location: "TP. Hồ Chí Minh",
    brand: "Niuben Hotpot",
    imageUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Trị giá 120.000đ",
    descriptionDetail: "Món chả sò điệp thơm ngon đặc trưng tại lẩu Niuben Hotpot sẽ được phục vụ hoàn toàn miễn phí cho nhóm đi từ 2 người.",
  },
  {
    id: "mreco-15pct",
    name: "E-Coupon giảm giá 15% cho hóa đơn từ 200.000đ tại Mr.Eco Healthy Food",
    points: 1200,
    category: "Ăn uống",
    giftType: "Voucher ăn uống",
    location: "Hà Nội",
    brand: "Mr.Eco Healthy",
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Giảm 15% hóa đơn",
    descriptionDetail: "Ăn lành sống sạch cùng Mr.Eco! Áp dụng giảm 15% cho mọi hóa đơn ăn uống thanh toán trực tiếp hoặc giao hàng từ 200.000đ trở lên.",
  },
  {
    id: "nowt-nuoc",
    name: "E-Coupon ưu đãi tặng 2 lon nước ngọt hoặc bia cho nhóm từ 4 khách tại Nowt",
    points: 800,
    category: "Ăn uống",
    giftType: "Voucher ăn uống",
    location: "Toàn quốc",
    brand: "Nowt Coffee",
    imageUrl: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Tặng 2 lon nước",
    descriptionDetail: "Thưởng thức bữa ăn tại Nowt với nhóm từ 4 người lớn trở lên để nhận ngay 02 lon đồ uống (nước ngọt hoặc bia) miễn phí.",
  },

  // 2. Golf
  {
    id: "golf-tan-son-nhat",
    name: "Sân Golf Tân Sơn Nhất - E-Coupon giảm giá 500K cho phí sân (Green Fee)",
    points: 8500,
    category: "Golf",
    giftType: "Voucher dịch vụ",
    location: "TP. Hồ Chí Minh",
    brand: "Tân Sơn Nhất Golf",
    imageUrl: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Giảm 500.000đ",
    descriptionDetail: "Áp dụng giảm trực tiếp trên phí ra sân (Green fee) cho các ngày trong tuần và cuối tuần tại Sân Golf Tân Sơn Nhất. Vui lòng đặt lịch trước 48 tiếng.",
  },
  {
    id: "golf-group-premium",
    name: "GolfGroup - Voucher giảm giá 1.000.000đ khi mua gậy và phụ kiện Golf cao cấp",
    points: 6000,
    category: "Golf",
    giftType: "Voucher mua sắm",
    location: "Toàn quốc",
    brand: "GolfGroup",
    imageUrl: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Giảm 1.000.000đ",
    descriptionDetail: "Áp dụng cho hóa đơn mua sắm trang thiết bị, gậy golf cao cấp chính hãng từ Callaway, TaylorMade, Honma tại toàn bộ showroom GolfGroup.",
  },

  // 3. Du lịch - Khách sạn
  {
    id: "vinpearl-resort",
    name: "Vinpearl Resorts - E-Coupon giảm giá 10% khi đặt phòng nghỉ dưỡng toàn hệ thống",
    points: 9500,
    category: "Du lịch - Khách sạn",
    giftType: "Voucher dịch vụ",
    location: "Toàn quốc",
    brand: "Vinpearl",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Giảm 10% dịch vụ",
    descriptionDetail: "Mã ưu đãi giảm 10% trên giá công bố khi đặt phòng khách sạn, villa nghỉ dưỡng qua ứng dụng hoặc website chính thức của Vinpearl.",
  },
  {
    id: "muong-thanh-suite",
    name: "Khách Sạn Mường Thanh - Thẻ ưu đãi giảm 500.000đ đặt phòng hạng Suite",
    points: 5500,
    category: "Du lịch - Khách sạn",
    giftType: "Voucher dịch vụ",
    location: "Toàn quốc",
    brand: "Mường Thanh",
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Giảm 500.000đ",
    descriptionDetail: "Trải nghiệm kỳ nghỉ cao cấp với phòng Executive Suite tại hệ thống khách sạn Mường Thanh, giảm giá trực tiếp khi check-in.",
  },

  // 4. Vui chơi - Giải trí
  {
    id: "cgv-combo",
    name: "CGV Cinemas - E-Voucher đổi trọn gói 02 vé xem phim 2D kèm bắp nước ngọt",
    points: 3500,
    category: "Vui chơi - Giải trí",
    giftType: "Voucher dịch vụ",
    location: "Toàn quốc",
    brand: "CGV Cinemas",
    imageUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Trị giá 320.000đ",
    descriptionDetail: "Đổi ngay vé xem phim 2D tại tất cả các cụm rạp CGV toàn quốc kèm theo một phần bắp ngọt lớn và hai lon nước ngọt tùy chọn.",
  },
  {
    id: "happy-concept-photography",
    name: "Tiệm Ảnh Happy - e-Coupon ưu đãi Tặng ảnh in 40x60 khi chụp 2 concept",
    points: 4000,
    category: "Vui chơi - Giải trí",
    giftType: "Voucher dịch vụ",
    location: "Hà Nội",
    brand: "Tiệm Ảnh Happy",
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Tặng ảnh gỗ cao cấp",
    descriptionDetail: "Tặng 01 ảnh ép gỗ cao cấp kích thước 40x60cm trị giá 500.000đ khi đăng ký gói chụp ảnh chân dung/nghệ thuật từ 2 concept trở lên.",
  },

  // 5. Sức khỏe và Làm đẹp
  {
    id: "seoul-spa-skincare",
    name: "Seoul Spa - Voucher ưu đãi chăm sóc da mặt chuyên sâu Hydro-Glow",
    points: 4500,
    category: "Sức khỏe và Làm đẹp",
    giftType: "Voucher dịch vụ",
    location: "Toàn quốc",
    brand: "Seoul Spa",
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Trị giá 600.000đ",
    descriptionDetail: "Gói trị liệu da mặt chuyên sâu 75 phút, cấp ẩm tầng sâu và tái tạo collagen tự nhiên tại Hệ thống Thẩm mỹ viện Seoul Spa.",
  },
  {
    id: "menard-japan-massage",
    name: "Menard Japan - Thẻ đặc quyền massage mặt và trị liệu thư giãn chuyên sâu",
    points: 8000,
    category: "Sức khỏe và Làm đẹp",
    giftType: "Voucher dịch vụ",
    location: "Hà Nội",
    brand: "Menard",
    imageUrl: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Đặc quyền VIP",
    descriptionDetail: "Dịch vụ massage mặt chuẩn Nhật Bản sử dụng dòng mỹ phẩm khoáng chất cao cấp giúp da săn chắc, mịn màng ngay từ lần trị liệu đầu tiên.",
  },

  // 6. Quà tặng - Dịch vụ khác
  {
    id: "btaskee-premium-cleaning",
    name: "bTaskee - e-Coupon giảm giá 50.000đ cho dịch vụ tổng dọn dẹp nhà cửa",
    points: 1500,
    category: "Quà tặng - Dịch vụ khác",
    giftType: "Voucher dịch vụ",
    location: "Toàn quốc",
    brand: "bTaskee",
    imageUrl: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Giảm 50.000đ",
    descriptionDetail: "Giảm ngay 50.000đ cho dịch vụ giúp việc nhà theo giờ, vệ sinh máy lạnh, giặt ủi, đi chợ trên ứng dụng bTaskee.",
  },
  {
    id: "potico-flower-coupon",
    name: "E-Coupon ưu đãi giảm 100K hóa đơn hàng từ 500K tại Website Potico.vn",
    points: 1000,
    category: "Quà tặng - Dịch vụ khác",
    giftType: "Voucher mua sắm",
    location: "Toàn quốc",
    brand: "Potico.vn",
    imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Giảm 100.000đ",
    descriptionDetail: "Áp dụng cho mọi đơn hàng hoa và quà tặng tại Potico.vn có giá trị từ 500.000đ trở lên. Không áp dụng cùng lúc với các chương trình khuyến mại khác.",
  },

  // 7. Khóa học - Đào tạo
  {
    id: "unica-online-course",
    name: "Unica - E-Coupon miễn phí 100% khóa học trực tuyến kỹ năng mềm tự chọn",
    points: 2500,
    category: "Khóa học - Đào tạo",
    giftType: "Voucher dịch vụ",
    location: "Toàn quốc",
    brand: "Unica",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Miễn phí khóa học",
    descriptionDetail: "Nhận mã kích hoạt học tập trọn đời cho một khóa học bất kỳ về Kỹ năng mềm, Kinh doanh, Thiết kế hoặc Ngoại ngữ trên Unica.vn.",
  },
  {
    id: "vus-ielts-tuition",
    name: "Hệ Thống Anh Văn Hội Việt Mỹ VUS - Thẻ quà tặng giảm 2.000.000đ học phí",
    points: 7500,
    category: "Khóa học - Đào tạo",
    giftType: "Voucher dịch vụ",
    location: "Toàn quốc",
    brand: "VUS English",
    imageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Giảm 2.000.000đ học phí",
    descriptionDetail: "Áp dụng cho học viên đăng ký mới khóa học IELTS hoặc Tiếng Anh giao tiếp Quốc tế tại toàn bộ hệ thống trung tâm VUS trên toàn quốc.",
  },

  // 8. Thẻ tiện ích
  {
    id: "telecom-viettel-100k",
    name: "Thẻ nạp điện thoại Viettel mệnh giá 100.000đ (Nhận mã thẻ cào SMS)",
    points: 2000,
    category: "Thẻ tiện ích",
    giftType: "Voucher mua sắm",
    location: "Toàn quốc",
    brand: "Viettel",
    imageUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Mệnh giá 100.000đ",
    descriptionDetail: "Đổi lấy mã thẻ cào điện thoại Viettel 100.000đ gửi trực tiếp qua tin nhắn SMS đến số điện thoại đăng ký tài khoản của bạn.",
  },
  {
    id: "viettel-money-utility",
    name: "Viettel Money - E-Voucher giảm 50.000đ hóa đơn Điện/Nước/Internet",
    points: 1200,
    category: "Thẻ tiện ích",
    giftType: "Voucher mua sắm",
    location: "Toàn quốc",
    brand: "Viettel Money",
    imageUrl: "https://images.unsplash.com/photo-1548345680-f5475ea5df84?w=600&auto=format&fit=crop&q=80",
    originalPriceText: "Giảm 50.000đ hóa đơn",
    descriptionDetail: "Áp dụng giảm trừ trực tiếp khi thanh toán các loại hóa đơn sinh hoạt Điện, Nước, Truyền hình hoặc Internet Viettel qua ứng dụng Viettel Money.",
  }
];
